apiVersion: v1
kind: Pod
metadata:
  name: sample-rsq
spec:
  containers:
  - name: sample-rsq
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 1;done"]
    resources:
      requests:
        memory: "8Mi"
        cpu: "80m"
      limits:
        memory: "8Mi"
        cpu: "80m"
  priorityClassName: high
